### ISSUE TITLE
imylu/imylu/utils/load_data.py/

### ISSUE THREAD

**Issue by Jacob-xyb** [tushushu/imylu#10]
def gen_data(low, high, n_rows, n_cols=None):
```
Returns:       
        list -- 1d or 2d list with int
```

but in `imylu/imylu/utils/preprocessing.py/def min_max_scale(X):` X is ndarray .

and you can see `imylu/examples/kd_tree_example.py/` 's line 51~line 53
```
X = gen_data(low, high, n_rows, n_cols)        
y = gen_data(low, high, n_rows)        
Xi = gen_data(low, high, n_cols)
```
I think just add a line in def gen_data():
```
def gen_data(low, high, n_rows, n_cols=None):
    """Generate dataset randomly.
    Arguments:
        low {int} -- The minimum value of element generated.
        high {int} -- The maximum value of element generated.
        n_rows {int} -- Number of rows.
        n_cols {int} -- Number of columns.
    Returns:
        list -- 1d or 2d list with int
    """
    if n_cols is None:
        ret = [randint(low, high) for _ in range(n_rows)]
    else:
        ret = [[randint(low, high) for _ in range(n_cols)]
               for _ in range(n_rows)]
    ret = array(ret)  # This is my add.
    return ret
```
Maybe I ignore something in somewhere, thanks!
## 打扰了，非常感谢~

**Comment by tushushu** [comment]
Thanks @Jacob-xyb, this repo was originally implemented by native python objects like set, list, dict, and then re-implemented by numpy. So the doc-strings in this repo may need to be updated. I feel like I should find some time to update all the doc-strings with mistakes, and not make people confused.

**Comment by tushushu** [comment]
After reading my codes again, I found that some of the algorithms are still implemented by native Python objects like array but not ndarray. So that's might be the reason why `gen_data` function is returning with List.

**Comment by Jacob-xyb** [comment]
Thanks for your reply!
