### ISSUE TITLE
矩阵分解, 相乘出现负值问题探讨

### ISSUE THREAD

**Issue by ShutaoTang** [tushushu/imylu#12]
博主你好，谢谢你分享代码。代码特别适合学习，书写整洁。
我是通过ALS搜索到您的代码，借此我想请教你一个问题。

ALS分解出来的两个矩阵，相乘之后，出现了很多负值，这样的负值怎么理解呢。举例如下：

```
userId,movieId,rating,timestamp
1,2,4.5,964982703
1,3,2.0,964981247
2,1,4.0,964982224
2,3,3.5,964983815
3,2,5.0,964982931
3,4,2.0,964982400
4,2,3.5,964980868
4,3,4.0,964982176
4,4,1.0,964984041

对应于评分矩阵
{{0,   4.5,  2,   0}, 
 {4.0, 0,  3.5,  0},
 {0,   5.0,  0,   2.0}, 
 {0,   3.5, 4.0, 1.0}}
```
通过你的代码计算结果如下

```python

model = ALS()
model.fit(X, k=2, max_iter=10)

## ===>

user_matrix = 
   [[0.7570282336382094, 0.03844973056986965, 0.8341276635923996, 0.7159946957782793],
    [0.2987763898981603, 1.2236650397020115, -0.09214284357731845, 0.661286003351013]]

item_matrix = 
   [[-0.9352925817978953, 5.779445419172115, 1.301780265376408, 1.4251036233547738], 
    [2.7179214250950294, -0.33085416701657533, 3.272648111651669, -0.2344265756021138]]

user_matrix.transpose x item_matrix = 
[[0.10400786028337483, 4.276351943480331, 1.9632744030892986, 1.0088025527850888],
 [3.2898636807717296, -0.1826365582074784, 4.054678181939848, -0.23206475458923115],
 [-1.0305904247583555, 4.851281148112146, 0.7842998282335908, 1.2103190870120526], 
 [1.1276588690551161, 3.919263034868889, 3.0962241552067207, 0.865343621997239]]

```

我通过Mathematica编程也计算出同样的结果

```Mathematica
R = {{0, 4.5, 2, 0}, {4.0, 0, 3.5, 0}, {0, 5.0, 0, 2.0}, {0, 3.5, 4.0,1.0}};
X = RandomReal[1, {4, 2}]
(* {{0.242376,0.511595}, {0.661005,0.105123}, {0.00835057,0.137917}, {0.980405,0.334949}} *)
Do[
   (* compute Y *)
   Xt = Transpose[X];
   Y = Transpose[LinearSolve[Xt.X, Xt.R]];
   (* compute X *)
   Yt = Transpose[Y];
   X = Transpose[LinearSolve[Yt.Y, Yt.Transpose[R]]],
   {i, 10}
]
```

很容易看到两个矩阵相乘出现了负值, 怎么理解这样的情况？谢谢

![image](https://user-images.githubusercontent.com/35004095/144694202-0d92ed2b-ce02-4205-88c8-c6926bcdad4b.png)

**Comment by tushushu** [comment]
@ShutaoTang 您好，首先出现负值是合理的，ALS其预测值是无法保证非负的，即使要预测的Y的真实值都是正数。因为最小二乘法的损失函数是MSE，那么预测值大于或者小于真实值都是可能的。
另外，从推荐系统的角度考虑，这个预测的评分值只是用来对推荐的物品进行排序，所以不需要一定是正数。简单说，只要把评分最高的物品推荐给用户即可。

**Comment by ShutaoTang** [comment]
@tushushu  谢谢您的回复，我昨天晚上也自己理解了一下，可以将负值理解为负分数，表示不喜欢。

在此，我还想请教一个问题。网上的很多人对ALS的推导很粗暴，有的损失函数的书写甚至是错误的。
这里，我以上面的评分矩阵为例

![image](https://user-images.githubusercontent.com/35004095/144745730-ff29ad4f-9025-4102-bbe9-b6bac5c7fe5c.png)

然后损失函数如下

![image](https://user-images.githubusercontent.com/35004095/144745761-4f8ba95a-070a-47f5-8cdc-1bb52465b134.png)

上面我直接对矩阵的分量进行求导，

![image](https://user-images.githubusercontent.com/35004095/144745781-b5103fb4-26a5-4006-933d-fd51e58ba3d5.png)

![image](https://user-images.githubusercontent.com/35004095/144745792-29e64996-71d6-4f95-a8ba-b1ec173ddc62.png)

这个矩阵形式就是博主代码里面实现使用到的形式，很明显它和我上面对分量求导得到的形式不一样。

但是我个人感觉两种形式有一定的联系，显然我上面推导的那一个肯定是正确的，那么下面一个感觉也对，但是又说不清原因在哪？

所有写下我的疑惑和博主探讨一下，谢谢

**Comment by tushushu** [comment]
我看了一下网上常见的推导，没看出什么问题。也许是我工作久了，淡忘了一些知识。有兴趣可以参考一下这篇文章，https://zhuanlan.zhihu.com/p/24709748
