### ISSUE TITLE
_get_split_mse 函数计算

### ISSUE THREAD

**Issue by chenxiaozheng** [tushushu/imylu#3]
_get_split_mse 中计算MSE的话  split_sqr_sum[0] - split_sum[0] * split_avg[0] 是不是应该为split_sqr_sum[0] - split_avg[0] * split_avg[0]   因为你是Y的实际值-Y的均值的平方

**Comment by VungleTienan** [comment]
这里利用的是统计学的方差公式，所以需要这样实现。

**Comment by tushushu** [comment]
这里利用的是统计学的方差公式，所以需要这样实现。
