### ISSUE TITLE
KD tree不比exhausted search的搜索速度快

### ISSUE THREAD

**Issue by cht649765744** [tushushu/imylu#4]
感谢您关于KD-tree的文章，这是在中文社区中能找到的最好的一篇！我有一个问题想请教您：当training data数据量增加时，您code中KD tree的NN搜索速度似乎并不比exhausted search的搜索速度快，复杂度并没有降到O(log(N))，请问这个问题是出在哪里了呢？  https://zhuanlan.zhihu.com/p/45346117

**Comment by tushushu** [comment]
之前的KD Tree实现有一个小问题，会导致一些多余的计算过程，现在已修正。感谢～
