### ISSUE TITLE
ALS Example不执行predication函数

### ISSUE THREAD

**Issue by MagiSuCoder** [tushushu/imylu#6]
ALS Example文件运行时，不执行predication函数，迭代十次之后直接关闭窗口，请问是什么情况？

**Comment by tushushu** [comment]
抱歉才回复。可以试下clone 0.1分支的代码，master分支可能有问题。最近工作忙，没有及时更改。




| |
刘铁男
邮箱：18591915960@163.com
|

签名由 网易邮箱大师 定制

在2019年05月09日 10:45，MagiSuCoder 写道：

ALS Example文件运行时，不执行predication函数，迭代十次之后直接关闭窗口，请问是什么情况？

**Comment by tushushu** [comment]
目前问题已修复。
