### ISSUE TITLE
regression_tree.py里面depth+1有必要吗

### ISSUE THREAD

**Issue by broadsun** [tushushu/imylu#9]
您好，请教下，https://github.com/tushushu/imylu/blob/master/imylu/tree/regression_tree.py 237行depth+1感觉没有必要啊

**Comment by tushushu** [comment]
其实没必要，有人认为树的深度是从1开始算，高度是从0开始算。这种教条的概念不用在意。




| |
Tienan Liu
|
|
邮箱：m18591915960@163.com
|

Signature is customized by Netease Mail Master

在2019年08月24日 11:54，broadsun 写道：

您好，请教下，https://github.com/tushushu/imylu/blob/master/imylu/tree/regression_tree.py 237行depth+1感觉没有必要啊
